---
title: "Emociones y parámetros acústicos"
subtitle: "Paper 3"
author: "Juliana Zapata"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.align = "center",
                      fig.width = 9)
```

# Bibliotecas

```{r}
library(tidyverse) # manejo y visualización de datos
library(janitor) # edición de nombres
library(readxl) # lectura de datos en excel
library(FactoMineR) # análisis multivariado
library(factoextra) # funciones extras para análisis multivariado
library(explor) # app shiny para ver resultados análisis multivariado
library(DT) # Imprimir tablas interactivas
library(corrplot) # correlograma
library(splines) # Agregar no linealidad a dispersiones
library(mgcv) # Modelos GAM
library(ggpubr)
library(psych)
library(autoplotly)

# Personalizano tema de ggplot2
theme_set(theme_minimal())
```

# Datos

```{r}
datos <- read_excel("QBA.xlsx", sheet = "Con y sin música")
datos
```
# Número de componentes

```{r}
resultados <- fa.parallel(x = datos %>%
                            select(
                              -c(
                                Semana,
                                Código,
                                Kind,
                                Distressed,
                                Apathetic,
                                Fearful,
                                Frustrated,
                                Bored
                              )
                            ))
```


# PCA - Varimax

- Número de componentes óptimo según el resultado anterior:

```{r}
num_comp <- resultados$ncomp
num_comp
```

- Ahora ajustamos el PCA con rotación *varimax*:

```{r}
pca <-
  pca(r = datos %>%
        select(
          -c(
            Semana,
            Código,
            Kind,
            Distressed,
            Apathetic,
            Fearful,
            Frustrated,
            Bored
          )
        ),
      nfactors = num_comp,
      rotate = "varimax")
pca
```

# Cargas

```{r}
library(autoplotly)
pca$loadings[, c(1, 2)] %>% autoplotly()
```


- Calculamos el promedio para las cargas (en valor absoluto) de los dos primeros componentes. 

```{r}
pca$loadings[, 1] %>% abs() %>% mean() # CP1
pca$loadings[, 2] %>% abs() %>% mean() # CP2
```

- Tabla de cargas:

```{r}
tabla_cargas <-
  pca$loadings[, c(1, 2)] %>%
  as.data.frame() %>%
  rownames_to_column(var = "adjetivo")
tabla_cargas
```

- Diagrama de cargas:

```{r, fig.width=9, fig.height=6}
fa.diagram(pca)
```

# ACP - Gráficos

## Variables

```{r}
library(ggrepel)
g1 <- tabla_cargas %>%
  ggplot(aes(x  = RC1, y = RC2, label = adjetivo, 
             select.var = list(contrib = 16), graph=FALSE,
               geom = c("text"), col.var = "black", labelsize=1,
               fill.var = "white", alpha.var = 0, col.quanti.sup = "blue",
               repel = TRUE)) +
  geom_text_repel() +
  geom_hline(yintercept = 0,size = 0.1, lty = 2, color = "Black") +
  geom_vline(xintercept = 0,size = 0.1, lty = 2, color = "Black") +
  theme(panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank()) +
  labs(x = "PC1 (34%)", y = "PC2 (22%)", title = "A")
g1
```

## Individuos

```{r, fig.width=10, fig.height=5}

g2 <-
  datos %>%
  mutate(
    Dim1 = pca$scores[, 1],
    Dim2 = pca$scores[, 2],
    Kind = fct_relevel(Kind,
                       levels = c("Enriched", "Barren"))
  ) %>%
  ggplot(data = ., aes(x = Dim1, y = Dim2, color = Kind)) +
  geom_point(size = 2) +
  scale_color_manual(values = c("orange", "skyblue")) +
  geom_vline(
    xintercept = 0,
    size = 0.1,
    lty = 2,
    color = "Black"
  ) +
  geom_hline(
    yintercept = 0,
    size = 0.1,
    lty = 2,
    color = "Black"
  ) +
  theme_light() +
  theme(
    panel.background = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_blank()
  ) +
  theme(legend.position = "right") +
  xlim(-3, 4) + ylim (-3.5, 3) +
  labs(
    x = "PC1 (34%)",
    y = "PC2 (22%)",
    title = "B",
    color = ""
  )
g2
```

## Variables + Individuos

```{r, fig.width=10, fig.height=5}
ggarrange(g1, g2)
```
